services:
  backend:
    build:
      context: ./backend
      platforms:
        - linux/arm64
    platform: linux/arm64
    ports:
      - "8000:8000"
    volumes:
      - ./data_library/db:/app/data
      - ./data_library/uploads:/app/uploads
    environment:
      - BABEL_DATA_DIR=/app/data
      - BABEL_UPLOAD_DIR=/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      platforms:
        - linux/arm64
    platform: linux/arm64
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8000
      - ORIGIN=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
